/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppProjectsCreateRouteImport } from './routes/app/projects/create'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/app/projects/$projectId/route'
import { Route as AppProjectsProjectIdSprintsRouteImport } from './routes/app/projects/$projectId/sprints'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/app/projects/$projectId/settings'
import { Route as AppProjectsProjectIdDashboardRouteImport } from './routes/app/projects/$projectId/dashboard'
import { Route as AppProjectsProjectIdCalendarRouteImport } from './routes/app/projects/$projectId/calendar'
import { Route as AppProjectsProjectIdBoardRouteImport } from './routes/app/projects/$projectId/board'
import { Route as AppProjectsProjectIdBacklogRouteImport } from './routes/app/projects/$projectId/backlog'
import { Route as AppProjectsProjectIdEpicsIndexRouteImport } from './routes/app/projects/$projectId/epics/index'
import { Route as AppProjectsProjectIdChatIndexRouteImport } from './routes/app/projects/$projectId/chat/index'
import { Route as AppProjectsProjectIdTasksTaskIdRouteImport } from './routes/app/projects/$projectId/tasks/$taskId'
import { Route as AppProjectsProjectIdEpicsEpicIdRouteImport } from './routes/app/projects/$projectId/epics/$epicId'
import { Route as AppProjectsProjectIdChatSessionIdRouteImport } from './routes/app/projects/$projectId/chat/$sessionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsCreateRoute = AppProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdSprintsRoute =
  AppProjectsProjectIdSprintsRouteImport.update({
    id: '/sprints',
    path: '/sprints',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdDashboardRoute =
  AppProjectsProjectIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdCalendarRoute =
  AppProjectsProjectIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdBoardRoute =
  AppProjectsProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdBacklogRoute =
  AppProjectsProjectIdBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdEpicsIndexRoute =
  AppProjectsProjectIdEpicsIndexRouteImport.update({
    id: '/epics/',
    path: '/epics/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdChatIndexRoute =
  AppProjectsProjectIdChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdTasksTaskIdRoute =
  AppProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdEpicsEpicIdRoute =
  AppProjectsProjectIdEpicsEpicIdRouteImport.update({
    id: '/epics/$epicId',
    path: '/epics/$epicId',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdChatSessionIdRoute =
  AppProjectsProjectIdChatSessionIdRouteImport.update({
    id: '/chat/$sessionId',
    path: '/chat/$sessionId',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/backlog': typeof AppProjectsProjectIdBacklogRoute
  '/app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/app/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/app/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/sprints': typeof AppProjectsProjectIdSprintsRoute
  '/app/projects/$projectId/chat/$sessionId': typeof AppProjectsProjectIdChatSessionIdRoute
  '/app/projects/$projectId/epics/$epicId': typeof AppProjectsProjectIdEpicsEpicIdRoute
  '/app/projects/$projectId/tasks/$taskId': typeof AppProjectsProjectIdTasksTaskIdRoute
  '/app/projects/$projectId/chat/': typeof AppProjectsProjectIdChatIndexRoute
  '/app/projects/$projectId/epics/': typeof AppProjectsProjectIdEpicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/backlog': typeof AppProjectsProjectIdBacklogRoute
  '/app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/app/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/app/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/sprints': typeof AppProjectsProjectIdSprintsRoute
  '/app/projects/$projectId/chat/$sessionId': typeof AppProjectsProjectIdChatSessionIdRoute
  '/app/projects/$projectId/epics/$epicId': typeof AppProjectsProjectIdEpicsEpicIdRoute
  '/app/projects/$projectId/tasks/$taskId': typeof AppProjectsProjectIdTasksTaskIdRoute
  '/app/projects/$projectId/chat': typeof AppProjectsProjectIdChatIndexRoute
  '/app/projects/$projectId/epics': typeof AppProjectsProjectIdEpicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/backlog': typeof AppProjectsProjectIdBacklogRoute
  '/app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/app/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/app/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/sprints': typeof AppProjectsProjectIdSprintsRoute
  '/app/projects/$projectId/chat/$sessionId': typeof AppProjectsProjectIdChatSessionIdRoute
  '/app/projects/$projectId/epics/$epicId': typeof AppProjectsProjectIdEpicsEpicIdRoute
  '/app/projects/$projectId/tasks/$taskId': typeof AppProjectsProjectIdTasksTaskIdRoute
  '/app/projects/$projectId/chat/': typeof AppProjectsProjectIdChatIndexRoute
  '/app/projects/$projectId/epics/': typeof AppProjectsProjectIdEpicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/create'
    | '/app/projects/'
    | '/app/projects/$projectId/backlog'
    | '/app/projects/$projectId/board'
    | '/app/projects/$projectId/calendar'
    | '/app/projects/$projectId/dashboard'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/sprints'
    | '/app/projects/$projectId/chat/$sessionId'
    | '/app/projects/$projectId/epics/$epicId'
    | '/app/projects/$projectId/tasks/$taskId'
    | '/app/projects/$projectId/chat/'
    | '/app/projects/$projectId/epics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/projects/$projectId'
    | '/app/projects/create'
    | '/app/projects'
    | '/app/projects/$projectId/backlog'
    | '/app/projects/$projectId/board'
    | '/app/projects/$projectId/calendar'
    | '/app/projects/$projectId/dashboard'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/sprints'
    | '/app/projects/$projectId/chat/$sessionId'
    | '/app/projects/$projectId/epics/$epicId'
    | '/app/projects/$projectId/tasks/$taskId'
    | '/app/projects/$projectId/chat'
    | '/app/projects/$projectId/epics'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/create'
    | '/app/projects/'
    | '/app/projects/$projectId/backlog'
    | '/app/projects/$projectId/board'
    | '/app/projects/$projectId/calendar'
    | '/app/projects/$projectId/dashboard'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/sprints'
    | '/app/projects/$projectId/chat/$sessionId'
    | '/app/projects/$projectId/epics/$epicId'
    | '/app/projects/$projectId/tasks/$taskId'
    | '/app/projects/$projectId/chat/'
    | '/app/projects/$projectId/epics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/create': {
      id: '/app/projects/create'
      path: '/projects/create'
      fullPath: '/app/projects/create'
      preLoaderRoute: typeof AppProjectsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId/sprints': {
      id: '/app/projects/$projectId/sprints'
      path: '/sprints'
      fullPath: '/app/projects/$projectId/sprints'
      preLoaderRoute: typeof AppProjectsProjectIdSprintsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/settings': {
      id: '/app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/app/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/dashboard': {
      id: '/app/projects/$projectId/dashboard'
      path: '/dashboard'
      fullPath: '/app/projects/$projectId/dashboard'
      preLoaderRoute: typeof AppProjectsProjectIdDashboardRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/calendar': {
      id: '/app/projects/$projectId/calendar'
      path: '/calendar'
      fullPath: '/app/projects/$projectId/calendar'
      preLoaderRoute: typeof AppProjectsProjectIdCalendarRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/board': {
      id: '/app/projects/$projectId/board'
      path: '/board'
      fullPath: '/app/projects/$projectId/board'
      preLoaderRoute: typeof AppProjectsProjectIdBoardRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/backlog': {
      id: '/app/projects/$projectId/backlog'
      path: '/backlog'
      fullPath: '/app/projects/$projectId/backlog'
      preLoaderRoute: typeof AppProjectsProjectIdBacklogRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/epics/': {
      id: '/app/projects/$projectId/epics/'
      path: '/epics'
      fullPath: '/app/projects/$projectId/epics/'
      preLoaderRoute: typeof AppProjectsProjectIdEpicsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/chat/': {
      id: '/app/projects/$projectId/chat/'
      path: '/chat'
      fullPath: '/app/projects/$projectId/chat/'
      preLoaderRoute: typeof AppProjectsProjectIdChatIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/tasks/$taskId': {
      id: '/app/projects/$projectId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/app/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof AppProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/epics/$epicId': {
      id: '/app/projects/$projectId/epics/$epicId'
      path: '/epics/$epicId'
      fullPath: '/app/projects/$projectId/epics/$epicId'
      preLoaderRoute: typeof AppProjectsProjectIdEpicsEpicIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/chat/$sessionId': {
      id: '/app/projects/$projectId/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/app/projects/$projectId/chat/$sessionId'
      preLoaderRoute: typeof AppProjectsProjectIdChatSessionIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
  }
}

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdBacklogRoute: typeof AppProjectsProjectIdBacklogRoute
  AppProjectsProjectIdBoardRoute: typeof AppProjectsProjectIdBoardRoute
  AppProjectsProjectIdCalendarRoute: typeof AppProjectsProjectIdCalendarRoute
  AppProjectsProjectIdDashboardRoute: typeof AppProjectsProjectIdDashboardRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdSprintsRoute: typeof AppProjectsProjectIdSprintsRoute
  AppProjectsProjectIdChatSessionIdRoute: typeof AppProjectsProjectIdChatSessionIdRoute
  AppProjectsProjectIdEpicsEpicIdRoute: typeof AppProjectsProjectIdEpicsEpicIdRoute
  AppProjectsProjectIdTasksTaskIdRoute: typeof AppProjectsProjectIdTasksTaskIdRoute
  AppProjectsProjectIdChatIndexRoute: typeof AppProjectsProjectIdChatIndexRoute
  AppProjectsProjectIdEpicsIndexRoute: typeof AppProjectsProjectIdEpicsIndexRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdBacklogRoute: AppProjectsProjectIdBacklogRoute,
    AppProjectsProjectIdBoardRoute: AppProjectsProjectIdBoardRoute,
    AppProjectsProjectIdCalendarRoute: AppProjectsProjectIdCalendarRoute,
    AppProjectsProjectIdDashboardRoute: AppProjectsProjectIdDashboardRoute,
    AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
    AppProjectsProjectIdSprintsRoute: AppProjectsProjectIdSprintsRoute,
    AppProjectsProjectIdChatSessionIdRoute:
      AppProjectsProjectIdChatSessionIdRoute,
    AppProjectsProjectIdEpicsEpicIdRoute: AppProjectsProjectIdEpicsEpicIdRoute,
    AppProjectsProjectIdTasksTaskIdRoute: AppProjectsProjectIdTasksTaskIdRoute,
    AppProjectsProjectIdChatIndexRoute: AppProjectsProjectIdChatIndexRoute,
    AppProjectsProjectIdEpicsIndexRoute: AppProjectsProjectIdEpicsIndexRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
  AppProjectsCreateRoute: typeof AppProjectsCreateRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
  AppProjectsCreateRoute: AppProjectsCreateRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
